"""Provenance: always embedded on every export (P0, no toggle).

Every export carries: app + version, engine + model version, design preset
name + full parameter hash, seed, script text SHA-256, generation timestamp,
and an explicit "synthetic audio" flag. Plus the loudness report (integrated
LUFS, true peak, LRA).

Embedding targets: WAV custom RIFF chunk, MP3 ID3v2 TXXX/COMM frames,
M4A MP4 metadata (via mutagen), and a sidecar JSON next to every file.
C2PA where trivially supported (P1+); the custom metadata + sidecar is the
guaranteed baseline. Inaudible watermarking (AudioSeal/Perth) is P2 opt-in.
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
from dataclasses import asdict, dataclass, field

from .. import APP_NAME, APP_VERSION, SYNTHETIC_FLAG


@dataclass
class Provenance:
    app: str = APP_NAME
    app_version: str = APP_VERSION
    synthetic: bool = True
    synthetic_flag: str = SYNTHETIC_FLAG
    engine_id: str = ""
    engine_version: str = ""
    model_id: str = ""
    model_version: str = ""
    design_id: str = ""
    design_name: str = ""
    design_params_hash: str = ""
    seed: int | None = None
    script_sha256: str = ""
    generated_at: str = ""
    loudness: dict = field(default_factory=dict)
    layers: dict = field(default_factory=dict)   # e.g. {"b_instruct": "..."}

    def __post_init__(self) -> None:
        if not self.generated_at:
            self.generated_at = _dt.datetime.now(_dt.timezone.utc).isoformat(
                timespec="seconds"
            )

    def to_dict(self) -> dict:
        return asdict(self)

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, sort_keys=True)

    def params_hash(self) -> str:
        """Stable hash of the full provenance (for library indexing)."""
        blob = json.dumps(self.to_dict(), sort_keys=True).encode()
        return hashlib.sha256(blob).hexdigest()[:16]


def write_sidecar(prov: Provenance, path: str) -> str:
    sidecar = path + ".presence.json"
    with open(sidecar, "w", encoding="utf-8") as f:
        f.write(prov.to_json())
    return sidecar


def embed_wav(prov: Provenance, wav_path: str) -> None:
    """Append a custom 'PSYN' RIFF chunk (provenance JSON) + LIST INFO tags."""
    import struct
    payload = prov.to_json().encode("utf-8")

    with open(wav_path, "rb") as f:
        data = f.read()
    # validate RIFF/WAVE
    if data[:4] != b"RIFF" or data[8:12] != b"WAVE":
        raise ValueError("not a RIFF/WAVE file")
    # strip any previous PSYN chunk
    chunks = []
    pos = 12
    while pos + 8 <= len(data):
        cid = data[pos:pos + 4]
        size = struct.unpack("<I", data[pos + 4:pos + 8])[0]
        body = data[pos + 8:pos + 8 + size]
        pos += 8 + size + (size % 2)
        if cid != b"PSYN":
            chunks.append((cid, body))
    psyn = b"PSYN" + struct.pack("<I", len(payload)) + payload
    if len(psyn) % 2:
        psyn += b"\x00"

    def _sub(cid: bytes, text: bytes) -> bytes:
        return cid + struct.pack("<I", len(text)) + text

    icmt = b"synthetic audio - cloned own voice - see .presence.json"
    icrd = prov.generated_at[:19].encode()
    info_body = (
        b"INFO"
        + _sub(b"INAM", b"Presence Studio (synthetic voice)")
        + _sub(b"IART", b"Presence Studio")
        + _sub(b"ICMT", icmt)
        + _sub(b"ICRD", icrd)
    )
    info = b"LIST" + struct.pack("<I", len(info_body)) + info_body
    out = bytearray()
    out += b"RIFF"
    total = 4 + len(info) + sum(len(b) + 8 for _c, b in chunks) + len(psyn)
    out += struct.pack("<I", total)
    out += b"WAVE"
    # keep fmt/data first (they are in `chunks` in original order)
    for cid, body in chunks:
        out += cid + struct.pack("<I", len(body)) + body
        if len(body) % 2:
            out += b"\x00"
    out += psyn
    with open(wav_path, "wb") as f:
        f.write(bytes(out))


def embed_mp3(prov: Provenance, mp3_path: str) -> None:
    from mutagen.id3 import ID3, TXXX, COMM, TIT2, TCON
    try:
        tags = ID3(mp3_path)
    except Exception:
        tags = ID3()
    tags["TIT2"] = TIT2(encoding=3, text="Presence Studio (synthetic voice)")
    tags["TCON"] = TCON(encoding=3, text="synthetic audio")
    tags["PSYN"] = TXXX(encoding=3, desc="presence-provenance",
                        text=prov.to_json())
    tags["COMM"] = COMM(encoding=3, language="eng",
                        desc="provenance",
                        text="Synthetic audio generated by Presence Studio. "
                             f"Engine {prov.engine_id} {prov.engine_version}. "
                             f"Design {prov.design_name}. See sidecar JSON.")
    tags.save(mp3_path)


def embed_m4a(prov: Provenance, m4a_path: str) -> None:
    from mutagen.mp4 import MP4
    tags = MP4(m4a_path)
    tags["\xa9nam"] = ["Presence Studio (synthetic voice)"]
    tags["\xa9cmt"] = ["Synthetic audio generated by Presence Studio."]
    # mutagen freeform keys are '----:mean:name' (three parts) and the
    # value must be bytes
    tags["----:com.presence.studio:provenance"] = [prov.to_json().encode("utf-8")]
    tags.save(m4a_path)
